.TH noted 1 noted\-VERSION
.SH NAME
noted \- Minimalistic note manager 
.SH SYNOPSIS
.B noted
.RB [ \-l ]
.RB [ \-i ]
.RB [ \-v ]
.RB [ \-h ]
.RB [ \-I ]
.RB [ \-Q ]
.RB [ \-R ]

.SH DESCRIPTION
noted is a minimalistic command line note manager written in C. It uses EDITOR environment variable to open notes and respects XDG variables to determine the store directory. It also supports markdown and plaintext notes. It is a simple and easy to use note manager with providing basic functionalities like adding, removing, and listing notes.
.SH OPTIONS

.TP
.B \-l
Lists the notes in the directory in a tree format.

.TP
.B \-i
Prints the directory where the notes are stored.

.TP
.B \-v
Prints the version of the program.

.TP
.B \-h
Shows the help message.

.TP
.B \-I [filename]
Creates a new note with the name specified in the filename.

.TP
.B \-Q [filename]
Searches for the note with specified name and prints its path to the stdout.

.TP
.B \-R [filename]
Removes the note specified in the filename.

.TP
.B \-S [filename]
Prints the content of the note specified in the filename.

.SH AUTHOR
Made by Night Kaly
.B <night@night0721.xyz>
